# Generated by Django 5.2.17 on 2026-08-19 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

BASELINE_GROUPS = (
    "Discover Qellem — System Administrators",
    "Discover Qellem — Managing Editors",
    "Discover Qellem — Subject Editors",
    "Discover Qellem — News and Feed Editors (Reserved)",
    "Discover Qellem — Translators",
    "Discover Qellem — Language Reviewers",
    "Discover Qellem — Fact and Source Reviewers",
    "Discover Qellem — Media Managers",
    "Discover Qellem — Finance Viewers (Reserved)",
    "Discover Qellem — Public-Submission Reviewers (Reserved)",
)


def create_baseline_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for group_name in BASELINE_GROUPS:
        Group.objects.get_or_create(name=group_name)


def remove_baseline_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=BASELINE_GROUPS).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("places", "0003_geographyindexpage_geographyprofilepage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system_admin", "System administrator"),
                            ("managing_editor", "Managing editor"),
                            ("subject_editor", "Subject editor"),
                            ("news_editor", "News and feed editor (reserved)"),
                            ("translator", "Translator"),
                            ("language_reviewer", "Language reviewer"),
                            ("fact_reviewer", "Fact and source reviewer"),
                            ("media_manager", "Media manager"),
                            ("finance_viewer", "Finance viewer (reserved)"),
                            (
                                "submission_reviewer",
                                "Public-submission reviewer (reserved)",
                            ),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("home_zone", "Combined homepage and zone profile"),
                            ("geography", "Geography profiles and identities"),
                            (
                                "history_culture",
                                "History, naming, culture, and heritage",
                            ),
                            ("people", "People"),
                            ("glossary_language", "Glossary and language"),
                            ("statistics", "Dated statistics"),
                            ("sources", "Private sources and citations"),
                            ("media", "Media and rights"),
                            ("partners", "Sponsors and collaborators"),
                            ("news_feed", "News and feed (reserved)"),
                            ("finance", "Finance (reserved)"),
                            ("public_submissions", "Public submissions (reserved)"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("om", "Afaan Oromoo"),
                            ("en", "English"),
                            ("both", "Both languages / locale-neutral record"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("submit", "Submit for review"),
                            ("review", "Review"),
                            ("approve", "Approve review"),
                            ("publish", "Publish"),
                            ("archive", "Archive or unpublish"),
                            ("manage_media", "Manage media"),
                        ],
                        max_length=16,
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty only for a grant with no scheduled end.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable immediately to revoke this assignment.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Required administrative reason for this grant."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geography",
                    models.ForeignKey(
                        help_text="The Qellem Wallaggaa zone grants zone-wide scope. A woreda or the town administration grants only that geography.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editorial_assignments",
                        to="places.geography",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_editorial_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_staff": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editorial_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "scoped editorial assignment",
                "verbose_name_plural": "scoped editorial assignments",
                "ordering": [
                    "user__username",
                    "subject",
                    "geography__display_order",
                    "action",
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "subject", "action"],
                        name="editorial_scope_lookup_idx",
                    ),
                    models.Index(
                        fields=["starts_at", "ends_at"],
                        name="editorial_scope_dates_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="editorial_scope_end_after_start",
                    )
                ],
            },
        ),
        migrations.RunPython(create_baseline_groups, remove_baseline_groups),
    ]
