# Generated by Django 5.2.17 on 2026-08-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        help_text="The approved Afaan Oromoo place name. It remains unchanged in every public language.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable canonical URL segment; do not replace it with an alias.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("zone", "Zone"),
                            ("woreda", "Woreda"),
                            ("town", "Town administration"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("historical", "Historical")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "administrative_notes",
                    models.TextField(
                        blank=True,
                        help_text="Private administrative notes; never part of public output.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for Qellem Wallaggaa. Woredas and the town administration must use Qellem Wallaggaa as parent.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="places.geography",
                    ),
                ),
            ],
            options={
                "verbose_name": "geography",
                "verbose_name_plural": "geographies",
                "ordering": ["display_order", "canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="GeographyAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Older or alternative form; never displayed as the canonical name.",
                        max_length=120,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Optional old URL segment used for a redirect.",
                        max_length=120,
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("spelling", "Alternative spelling"),
                            ("legacy_slug", "Legacy URL slug"),
                            ("historical", "Historical name"),
                            ("other", "Other"),
                        ],
                        default="spelling",
                        max_length=16,
                    ),
                ),
                (
                    "language_context",
                    models.CharField(
                        choices=[
                            ("und", "Unspecified"),
                            ("om", "Afaan Oromoo"),
                            ("en", "English"),
                        ],
                        default="und",
                        max_length=3,
                    ),
                ),
                (
                    "redirect_enabled",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Redirect this alias slug to the canonical geography route."
                        ),
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Private explanation or evidence for this alias.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geography",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="places.geography",
                    ),
                ),
            ],
            options={
                "verbose_name": "geography alias",
                "verbose_name_plural": "geography aliases",
                "ordering": ["geography__display_order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="geography",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("level", "zone"), ("parent__isnull", True)),
                    models.Q(
                        ("level__in", ["woreda", "town"]), ("parent__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="places_geography_level_parent_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="geographyalias",
            constraint=models.UniqueConstraint(
                fields=("geography", "name", "language_context"),
                name="places_alias_unique_name_context",
            ),
        ),
        migrations.AddConstraint(
            model_name="geographyalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                fields=("slug",),
                name="places_alias_unique_nonempty_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="geographyalias",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("redirect_enabled", False),
                    models.Q(
                        ("is_active", True), models.Q(("slug", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="places_alias_redirect_requires_active_slug",
            ),
        ),
    ]
