# Generated by Django 5.2.17 on 2026-08-19 14:50

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_seed_canonical_geographies'),
        ('provenance', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='GeographyProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('overview', wagtail.fields.RichTextField(blank=True)),
                ('naming_origin', wagtail.fields.RichTextField(blank=True)),
                ('history', wagtail.fields.RichTextField(blank=True)),
                ('area_location', wagtail.fields.RichTextField(blank=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Only an image with approved rights may be selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('geography', models.ForeignKey(limit_choices_to={'level__in': ['woreda', 'town']}, on_delete=django.db.models.deletion.PROTECT, related_name='profile_page_translations', to='places.geography')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DatedStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_om', models.CharField(max_length=255, verbose_name='Afaan Oromoo indicator')),
                ('indicator_en', models.CharField(blank=True, max_length=255, verbose_name='English indicator')),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit_om', models.CharField(max_length=120, verbose_name='Afaan Oromoo unit')),
                ('unit_en', models.CharField(blank=True, max_length=120, verbose_name='English unit')),
                ('subgroup_om', models.CharField(blank=True, max_length=255, verbose_name='Afaan Oromoo subgroup or definition')),
                ('subgroup_en', models.CharField(blank=True, max_length=255, verbose_name='English subgroup or definition')),
                ('reference_year_ec', models.CharField(help_text='For example: 2016 E.C.', max_length=20)),
                ('reference_year_gc', models.CharField(help_text='For example: 2023/24 G.C.', max_length=20)),
                ('method_note_om', models.TextField(blank=True, verbose_name='Afaan Oromoo method or explanatory note')),
                ('method_note_en', models.TextField(blank=True, verbose_name='English method or explanatory note')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('in_review', 'In review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=12)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dated_statistics', to='places.geography')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_dated_statistics', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dated_statistics', to='provenance.sourcerecord')),
            ],
            options={
                'verbose_name': 'dated statistic',
                'verbose_name_plural': 'dated statistics',
                'ordering': ['geography__display_order', 'indicator_om', '-reference_year_ec'],
                'constraints': [models.UniqueConstraint(fields=('geography', 'indicator_om', 'subgroup_om', 'reference_year_ec', 'reference_year_gc'), name='places_statistic_unique_snapshot')],
            },
        ),
    ]
