# Generated by Django 5.2.17 on 2026-08-21 23:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_seed_zone_notable_people'),
        ('places', '0003_geographyindexpage_geographyprofilepage_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographyprofilepage',
            name='attractions_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='English attractions'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='attractions_om',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo attractions'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='culture_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='English culture'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='culture_om',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo culture'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='economy_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='English economy'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='economy_om',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo economy'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='geography_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='English geography description'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='geography_om',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo geography description'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Only an image with approved rights may be selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='history_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='English history'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='history_om',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo history'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='intro_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='English introduction'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='intro_om',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo introduction'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the woreda seat town.', null=True),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the woreda seat town.', null=True),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='notable_people',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='profile_pages', to='archive.person'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='quick_facts',
            field=models.JSONField(blank=True, default=list, help_text='List of objects shaped as {label_en, label_om, value, unit?, note_en?, note_om?}.'),
        ),
    ]
