# Generated by Django 5.2.17 on 2026-08-22 07:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_seed_woreda_profile_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographyprofilepage',
            name='attractions_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic attractions'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='culture_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic culture'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='economy_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic economy'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='geography_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic geography description'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='history_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic history'),
        ),
        migrations.AddField(
            model_name='geographyprofilepage',
            name='intro_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic introduction'),
        ),
    ]
