# Generated by Django 5.2.17 on 2026-08-19 14:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_seed_canonical_geographies'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='GlossaryTermPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_term', models.CharField(help_text='The authoritative Afaan Oromoo term used in every language.', max_length=255)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('proper_name', 'Proper name'), ('other', 'Other')], max_length=16)),
                ('definition', wagtail.fields.RichTextField(blank=True)),
                ('usage_example', wagtail.fields.RichTextField(blank=True)),
                ('related_terms', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='HistoryCultureIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PeopleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ArchiveEntryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('history', 'History'), ('naming', 'Name origin or meaning'), ('culture', 'Culture'), ('heritage', 'Heritage'), ('place', 'Place or landmark'), ('community_voice', 'Community voice'), ('oral_history', 'Oral history')], max_length=20)),
                ('summary', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('relevant_period', models.CharField(blank=True, help_text='Relevant date or period exactly as supported by the source.', max_length=160)),
                ('uncertainty_notes', wagtail.fields.RichTextField(blank=True, help_text='Public alternative accounts, qualifications, or uncertainty.')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Only an image with approved rights may be selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_entry_translations', to='places.geography')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DeceasedPersonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_name', models.CharField(help_text='The verified name used unchanged in every language.', max_length=255)),
                ('name_aliases', models.TextField(blank=True, help_text='Verified spelling or naming aliases, one per line.')),
                ('birth_date_or_period', models.CharField(blank=True, max_length=160)),
                ('death_date_or_period', models.CharField(help_text='Exact or qualified approximate death date/period.', max_length=160)),
                ('geographic_associations', wagtail.fields.RichTextField(blank=True)),
                ('occupations', wagtail.fields.RichTextField(blank=True)),
                ('summary', wagtail.fields.RichTextField(blank=True)),
                ('biography', wagtail.fields.RichTextField(blank=True)),
                ('public_significance', wagtail.fields.RichTextField(blank=True)),
                ('birthplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_born_here_translations', to='places.geography')),
                ('portrait', models.ForeignKey(blank=True, help_text='Only an image with approved rights may be selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
