# Generated by Django 5.2.17 on 2026-08-21 23:34

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CommunityStory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author_name', models.CharField(max_length=255)),
                ('story_om', wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo story')),
                ('story_en', wagtail.fields.RichTextField(blank=True, verbose_name='English story')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False, help_text='Unapproved stories are hidden from the anonymous public API even when the page is live.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_om', models.CharField(max_length=255, verbose_name='Afaan Oromoo title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='English title')),
                ('body_om', wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo body')),
                ('body_en', wagtail.fields.RichTextField(blank=True, verbose_name='English body')),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('location_text_om', models.CharField(blank=True, max_length=255, verbose_name='Afaan Oromoo location')),
                ('location_text_en', models.CharField(blank=True, max_length=255, verbose_name='English location')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Only an image with approved rights may be selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_om', models.CharField(max_length=255, verbose_name='Afaan Oromoo title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='English title')),
                ('body_om', wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo body')),
                ('body_en', wagtail.fields.RichTextField(blank=True, verbose_name='English body')),
                ('category', models.CharField(choices=[('development', 'Development / Misooma'), ('economy', 'Economy / Dinagdee'), ('environment', 'Environment / Naannoo'), ('minerals', 'Minerals / Mineraala'), ('agriculture', 'Agriculture / Qonna'), ('health', 'Health / Fayyaa'), ('education', 'Education / Barnoota'), ('culture', 'Culture / Aadaa'), ('trade', 'Trade / Daldala')], max_length=20)),
                ('published_date', models.DateField()),
                ('featured_image', models.ForeignKey(blank=True, help_text='Only an image with approved rights may be selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NewsArticleGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption_om', models.CharField(blank=True, max_length=255, verbose_name='Afaan Oromoo caption')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='English caption')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='archive.newsarticle')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
