# Generated by Django 5.2.17 on 2026-08-21 23:40

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_create_archive_index_page'),
        ('places', '0003_geographyindexpage_geographyprofilepage_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_om', models.CharField(max_length=255, verbose_name='Afaan Oromoo name')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='English name')),
                ('slug', models.SlugField(help_text='Stable identifier used by the public API; do not recycle.', max_length=255, unique=True)),
                ('birth_year', models.IntegerField(blank=True, help_text='Leave empty until the year is verified against a source.', null=True)),
                ('death_year', models.IntegerField(blank=True, help_text='Leave empty when the person is alive or the year is unverified.', null=True)),
                ('bio_om', wagtail.fields.RichTextField(blank=True, verbose_name='Afaan Oromoo biography')),
                ('bio_en', wagtail.fields.RichTextField(blank=True, verbose_name='English biography')),
                ('is_zone_notable', models.BooleanField(default=False, help_text='Show this person on zone-wide notable people listings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(blank=True, help_text='Only an image with approved rights may be selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'notable person',
                'verbose_name_plural': 'notable people',
                'ordering': ['name_om'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PersonPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('geography', models.ForeignKey(limit_choices_to={'level__in': ['woreda', 'town']}, on_delete=django.db.models.deletion.PROTECT, related_name='person_placements', to='places.geography')),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='archive.person')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='woredas',
            field=models.ManyToManyField(blank=True, related_name='notable_people', through='archive.PersonPlacement', to='places.geography'),
        ),
        migrations.AddConstraint(
            model_name='personplacement',
            constraint=models.UniqueConstraint(fields=('person', 'geography'), name='archive_person_placement_unique'),
        ),
    ]
