# Generated by Django 5.2.17 on 2026-08-22 00:13

import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_seed_inauguration_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_om', models.CharField(max_length=40, verbose_name='Afaan Oromoo year label')),
                ('year_en', models.CharField(blank=True, help_text='Optional while the English translation is pending.', max_length=40, verbose_name='English year label')),
                ('year_int', models.IntegerField(help_text='Numeric year used to order the timeline.')),
                ('title_om', models.CharField(max_length=255, verbose_name='Afaan Oromoo title')),
                ('title_en', models.CharField(blank=True, help_text='Optional while the English translation is pending.', max_length=255, verbose_name='English title')),
                ('text_om', models.TextField(verbose_name='Afaan Oromoo text')),
                ('text_en', models.TextField(blank=True, help_text='Optional while the English translation is pending.', verbose_name='English text')),
            ],
            options={
                'verbose_name': 'timeline event',
                'verbose_name_plural': 'timeline events',
                'ordering': ['year_int', 'pk'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
