# Generated by Django 5.2.17 on 2026-08-22 07:49

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_fill_inauguration_body_om'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitystory',
            name='story_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic story'),
        ),
        migrations.AddField(
            model_name='event',
            name='body_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic body'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_text_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='Amharic location'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='Amharic title'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic body'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='Amharic title'),
        ),
        migrations.AddField(
            model_name='newsarticlegalleryimage',
            name='caption_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='Amharic caption'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_am',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic biography'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='Amharic name'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='text_am',
            field=models.TextField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', verbose_name='Amharic text'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='Amharic title'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='year_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=40, verbose_name='Amharic year label'),
        ),
    ]
