# Generated by Django 5.2.17 on 2026-08-22 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_communitystory_story_am_event_body_am_and_more'),
        ('places', '0006_geographyprofilepage_attractions_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitystory',
            name='geography',
            field=models.ForeignKey(blank=True, help_text='Optional place this story is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_stories', to='places.geography'),
        ),
        migrations.AlterField(
            model_name='communitystory',
            name='author_name',
            field=models.CharField(blank=True, help_text='Optional; anonymous community submissions are allowed.', max_length=255),
        ),
    ]
