# Generated by Django 5.2.17 on 2026-08-19 14:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("places", "0002_seed_canonical_geographies"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaRights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        blank=True,
                        help_text="Photographer or creator, when known.",
                        max_length=255,
                    ),
                ),
                ("rights_owner_name", models.CharField(blank=True, max_length=255)),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        help_text="Person or organization that supplied the image.",
                        max_length=255,
                    ),
                ),
                (
                    "provenance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Private chain-of-custody and source notes.",
                    ),
                ),
                ("capture_date", models.DateField(blank=True, null=True)),
                ("capture_location", models.CharField(blank=True, max_length=255)),
                (
                    "permission_basis",
                    models.CharField(
                        choices=[
                            ("pending", "Not yet confirmed"),
                            ("verbal", "Verbal permission"),
                            ("written", "Written permission"),
                            ("license", "License"),
                            ("creator_owned", "Supplied by the rights-owning creator"),
                            ("public_domain", "Verified public domain"),
                            ("other", "Other documented basis"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("permission_date", models.DateField(blank=True, null=True)),
                (
                    "permitted_uses",
                    models.TextField(
                        blank=True,
                        help_text="State the approved channels and purposes, such as this website only.",
                    ),
                ),
                (
                    "restrictions",
                    models.TextField(
                        blank=True,
                        help_text="Private restrictions, expiry, cropping, or reuse conditions.",
                    ),
                ),
                ("credit_line", models.CharField(blank=True, max_length=255)),
                (
                    "caption_om",
                    models.TextField(blank=True, verbose_name="Afaan Oromoo caption"),
                ),
                (
                    "caption_en",
                    models.TextField(
                        blank=True,
                        help_text="Optional while English translation is pending.",
                        verbose_name="English caption",
                    ),
                ),
                (
                    "alt_text_om",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Afaan Oromoo alternative text",
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True,
                        help_text="Optional while English translation is pending.",
                        max_length=500,
                        verbose_name="English alternative text",
                    ),
                ),
                ("people_depicted", models.BooleanField(default=False)),
                ("minors_depicted", models.BooleanField(default=False)),
                (
                    "consent_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "No people depicted"),
                            ("pending", "Pending confirmation"),
                            ("confirmed", "Consent confirmed"),
                            ("not_required", "Documented as not required"),
                            ("restricted", "Restricted use"),
                            ("declined", "Consent declined"),
                        ],
                        default="not_applicable",
                        max_length=16,
                    ),
                ),
                (
                    "consent_notes",
                    models.TextField(
                        blank=True,
                        help_text="Private consent assessment where people appear.",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("in_review", "In review"),
                            ("approved", "Approved for permitted public uses"),
                            ("rejected", "Rejected"),
                            ("expired", "Approval expired or withdrawn"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Private media-review notes."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discover_qellem_rights",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_media_rights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "image provenance and rights record",
                "verbose_name_plural": "image provenance and rights records",
                "ordering": ["image__title"],
            },
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="Private stable identifier. The original writing must remain outside the CMS and Git repository.",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use an ID such as SRC-001 with at least three digits.",
                                regex="^SRC-[0-9]{3,}$",
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("issuing_organization", models.CharField(max_length=255)),
                (
                    "source_date_text",
                    models.CharField(
                        blank=True,
                        help_text="Date exactly as stated by the source, without converting it.",
                        max_length=80,
                    ),
                ),
                (
                    "source_calendar",
                    models.CharField(
                        choices=[
                            ("ec", "Ethiopian calendar (E.C.)"),
                            ("gc", "Gregorian calendar (G.C.)"),
                            ("both", "Both calendars"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("profile", "Administrative profile"),
                            ("report", "Report"),
                            ("brief", "Brief or summary"),
                            ("letter", "Letter or official correspondence"),
                            ("dataset", "Dataset or statistical table"),
                            ("web_page", "Web page"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("om", "Afaan Oromoo"),
                            ("en", "English"),
                            ("om_en", "Afaan Oromoo and English"),
                            ("other", "Other"),
                        ],
                        default="om",
                        max_length=10,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("history_naming", "History and naming"),
                            ("culture_heritage", "Culture and heritage"),
                            ("demographics", "Demographics and statistics"),
                            ("geography_places", "Geography and places"),
                            ("notable_people", "Deceased notable people"),
                            ("glossary_language", "Glossary and language"),
                            ("administration", "Administration"),
                            ("mixed", "Multiple subjects"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "private_description",
                    models.TextField(
                        help_text="Private catalogue summary; never expose this field publicly."
                    ),
                ),
                (
                    "permission_basis",
                    models.CharField(
                        choices=[
                            ("pending", "Not yet confirmed"),
                            ("verbal", "Verbal permission"),
                            ("written", "Written permission"),
                            ("license", "License"),
                            ("creator_owned", "Supplied by the rights-owning creator"),
                            ("public_domain", "Verified public domain"),
                            ("other", "Other documented basis"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("permission_confirmed_on", models.DateField(blank=True, null=True)),
                (
                    "permission_confirmation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Private record of who gave permission, to whom, and for what use.",
                    ),
                ),
                (
                    "sensitivity_status",
                    models.CharField(
                        choices=[
                            ("not_screened", "Not screened"),
                            ("in_review", "Screening in progress"),
                            ("cleared", "Cleared for editorial use"),
                            ("concerns", "Concerns require resolution"),
                            ("restricted", "Restricted"),
                        ],
                        default="not_screened",
                        max_length=16,
                    ),
                ),
                (
                    "sensitivity_notes",
                    models.TextField(
                        blank=True,
                        help_text="Private screening notes; never expose this field publicly.",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("in_review", "In review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=12,
                    ),
                ),
                ("verified_on", models.DateField(blank=True, null=True)),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Private fact/source review notes."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geography",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary geography, or leave empty when the source is not place-specific.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_records",
                        to="places.geography",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_source_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "private source record",
                "verbose_name_plural": "private source records",
                "ordering": ["source_id"],
            },
        ),
        migrations.CreateModel(
            name="SourceCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "claim_or_section",
                    models.TextField(
                        help_text="Private note identifying the claim, table, paragraph, or source section."
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending fact review"),
                            ("verified", "Claim verified"),
                            ("disputed", "Claim disputed"),
                            ("rejected", "Citation rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("verified_on", models.DateField(blank=True, null=True)),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Private fact-review decision notes."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citing_editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_source_citations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "fact_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_source_citations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citations",
                        to="provenance.sourcerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "private source citation",
                "verbose_name_plural": "private source citations",
                "ordering": ["source__source_id", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="provenance_citation_target_idx",
                    )
                ],
            },
        ),
    ]
