# Generated by Django 5.2.17 on 2026-08-19 14:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_configure_foundation'),
        ('places', '0002_seed_canonical_geographies'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contribute_summary',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='culture_summary',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='geography',
            field=models.ForeignKey(db_column='geography_slug', default='qellem-wallaggaa', limit_choices_to={'level': 'zone'}, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_translations', to='places.geography', to_field='slug'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Only an image with approved rights may be selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='history_summary',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text="Opening introduction in this page's language."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='naming_summary',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overview',
            field=wagtail.fields.RichTextField(blank=True, help_text="Authoritative zone overview in this page's language."),
        ),
    ]
