# Generated by Django 5.2.17 on 2026-08-19 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_kind', models.CharField(choices=[('organization', 'Organization'), ('person', 'Individual')], max_length=12)),
                ('display_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('display_mode', models.CharField(choices=[('name_only', 'Approved name only'), ('image_and_name', 'Approved logo or portrait with name')], default='name_only', max_length=16)),
                ('display_start', models.DateField(blank=True, null=True)),
                ('display_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('public_display_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved for public display'), ('rejected', 'Rejected'), ('expired', 'Approval expired or withdrawn')], default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Private evidence and decision notes; never public output.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_om', models.CharField(blank=True, max_length=255, verbose_name='Afaan Oromoo contribution or role')),
                ('role_en', models.CharField(blank=True, max_length=255, verbose_name='English contribution or role')),
                ('affiliation_om', models.CharField(blank=True, max_length=255, verbose_name='Afaan Oromoo affiliation')),
                ('affiliation_en', models.CharField(blank=True, max_length=255, verbose_name='English affiliation')),
                ('contribution_period', models.CharField(blank=True, max_length=160)),
                ('description_om', models.TextField(blank=True, verbose_name='Afaan Oromoo public description')),
                ('description_en', models.TextField(blank=True, verbose_name='English public description')),
                ('consent_status', models.CharField(choices=[('not_applicable', 'No people depicted'), ('pending', 'Pending confirmation'), ('confirmed', 'Consent confirmed'), ('not_required', 'Documented as not required'), ('restricted', 'Restricted use'), ('declined', 'Consent declined')], default='not_applicable', max_length=16)),
                ('consent_notes', models.TextField(blank=True, help_text='Private public-recognition and portrait consent evidence.')),
                ('image', models.ForeignKey(blank=True, help_text='Approved public logo or portrait.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collaborator',
                'verbose_name_plural': 'collaborators',
                'ordering': ['display_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_kind', models.CharField(choices=[('organization', 'Organization'), ('person', 'Individual')], max_length=12)),
                ('display_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('display_mode', models.CharField(choices=[('name_only', 'Approved name only'), ('image_and_name', 'Approved logo or portrait with name')], default='name_only', max_length=16)),
                ('display_start', models.DateField(blank=True, null=True)),
                ('display_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('public_display_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved for public display'), ('rejected', 'Rejected'), ('expired', 'Approval expired or withdrawn')], default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Private evidence and decision notes; never public output.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recognition_text_om', models.TextField(blank=True, verbose_name='Afaan Oromoo recognition text')),
                ('recognition_text_en', models.TextField(blank=True, help_text='Optional while English translation is pending.', verbose_name='English recognition text')),
                ('sponsorship_level', models.CharField(blank=True, max_length=120)),
                ('image', models.ForeignKey(blank=True, help_text='Approved public logo or portrait.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
                'ordering': ['display_order', 'display_name'],
            },
        ),
    ]
