# Generated by Django 5.2.17 on 2026-08-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_seed_sponsors_and_supporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='display_name_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='Amharic display name'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='display_name_en',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='English display name'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='display_name_am',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='Amharic display name'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='display_name_en',
            field=models.CharField(blank=True, help_text='Optional translation; Afaan Oromoo stays authoritative.', max_length=255, verbose_name='English display name'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='display_name',
            field=models.CharField(help_text='Required canonical Afaan Oromoo public name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='display_name',
            field=models.CharField(help_text='Required canonical Afaan Oromoo public name.', max_length=255),
        ),
    ]
